### ISSUE TITLE
Integration fails for release 2021-1 if more than one team is defined 

### ISSUE THREAD

**Issue by visma-kimhjortholm** [Customatics/Leaptest-Integration#6]
When more than one team is defined in LeapWork the integrations between Teamcity and LeapWork  fails with following error
Code: 500 Status: Application error occured. Error code: -1!

Error can be avoided by only having one team defined, obviously meaning that this feature in 2021-1 release can not be used until this issue is resolved

Job in TeamCity fails with following error code
![2021-02-17_21-54-57](https://user-images.githubusercontent.com/58805979/108396630-57ee9580-7217-11eb-90b3-9ea9bd430efa.png)

 

```
Code: 500 Status: Application error occured. Error code: -1!
Controller responded with errors! Please check controller logs and try again! If does not help, try to restart controller. 
```

Checking controller log following entries can be seen

`[11976] LeapTest.AutomationController.Repositories.ApiActors.ApiScheduleStatusByRunIdWorkerActor 2021-02-17 21:19:02.9018 - Error
Message: Could not get status by RunId
LeapTest.AutomationController.API.v3.ApiException: Incorrect team id
   at LeapTest.AutomationController.API.v3.ApiHelper.GetTeamActor[T](Guid teamId) in C:\Azure_Agents\win4\_work\2\s\Main\LeapTest.AutomationController\API\v3\ApiHelper.cs:line 298
   at LeapTest.AutomationController.Repositories.ApiActors.ApiScheduleStatusByRunIdWorkerActor.GetRunStatus(GetRunStatusApiMessage msg) in C:\Azure_Agents\win4\_work\2\s\Main\LeapTest.AutomationController\Repositories\ApiActors\ApiScheduleStatusByRunIdWorkerActor.cs:line 69    at LeapTest.AutomationController.API.v3.ApiHelper.GetTeamActor[T](Guid teamId) in C:\Azure_Agents\win4\_work\2\s\Main\LeapTest.AutomationController\API\v3\ApiHelper.cs:line 298
   at LeapTest.AutomationController.Repositories.ApiActors.ApiScheduleStatusByRunIdWorkerActor.GetRunStatus(GetRunStatusApiMessage msg) in C:\Azure_Agents\win4\_work\2\s\Main\LeapTest.AutomationController\Repositories\ApiActors\ApiScheduleStatusByRunIdWorkerActor.cs:line 69`
![2021-02-17_21-08-44](https://user-images.githubusercontent.com/58805979/108396635-58872c00-7217-11eb-8997-ec18537dde0c.png)

I suspect API (by luck) return a correct answer when only one team is defined in LeapWork

**Comment by visma-kimhjortholm** [comment]
No response here, will try to raise issue via Leapwork support chat

**Comment by visma-kimhjortholm** [comment]
Leapwork working on a new version of the integration, support will check whether issue persist in the new  version.
No timeline provided for the new version
